// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfQ3JChC1a-gQ1yoJT1CV8tEOTCmErhnI',
    appId: '1:924983553465:web:70d7cb6ae494d342bc1a68',
    messagingSenderId: '924983553465',
    projectId: 'player-69c6e',
    authDomain: 'player-69c6e.firebaseapp.com',
    storageBucket: 'player-69c6e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHhcNrRdgkYD9S6zNtYYGNoe6SbWFUn8A',
    appId: '1:924983553465:android:6929b41dba27240ebc1a68',
    messagingSenderId: '924983553465',
    projectId: 'player-69c6e',
    storageBucket: 'player-69c6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxyd88kElR0qJBubeulwYx_3z8mo1qWNU',
    appId: '1:924983553465:ios:2436bcff7f114b8dbc1a68',
    messagingSenderId: '924983553465',
    projectId: 'player-69c6e',
    storageBucket: 'player-69c6e.firebasestorage.app',
    iosBundleId: 'com.example.assessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxyd88kElR0qJBubeulwYx_3z8mo1qWNU',
    appId: '1:924983553465:ios:2436bcff7f114b8dbc1a68',
    messagingSenderId: '924983553465',
    projectId: 'player-69c6e',
    storageBucket: 'player-69c6e.firebasestorage.app',
    iosBundleId: 'com.example.assessment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfQ3JChC1a-gQ1yoJT1CV8tEOTCmErhnI',
    appId: '1:924983553465:web:ead029afaae45dc3bc1a68',
    messagingSenderId: '924983553465',
    projectId: 'player-69c6e',
    authDomain: 'player-69c6e.firebaseapp.com',
    storageBucket: 'player-69c6e.firebasestorage.app',
  );
}
